# Generated by Django 5.2 on 2025-05-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0006_alter_staj_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='staj',
            name='admin_onaylandi',
            field=models.BooleanField(default=False),
        ),
    ]
