# Generated by Django 5.2 on 2025-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0003_alter_stajdefteri_gun_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='staj',
            name='durum',
            field=models.CharField(default='Beklemede', max_length=20),
        ),
    ]
