# Generated by Django 5.2 on 2025-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0004_staj_durum'),
    ]

    operations = [
        migrations.CreateModel(
            name='HesapTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isim', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('OGRENCI', 'Öğrenci'), ('KURUM', 'Kurum')], max_length=10)),
                ('onaylandi', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
