# Generated by Django 5.2 on 2025-04-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0002_staj_kurum_aciklama_staj_kurum_onaylandi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stajdefteri',
            name='gun_no',
            field=models.DateField(),
        ),
    ]
