# Generated by Django 5.2 on 2025-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0005_hesaptalep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staj',
            name='durum',
            field=models.CharField(choices=[('Beklemede', 'Beklemede'), ('Aktif', 'Aktif'), ('Tamamlandı', 'Tamamlandı'), ('Reddedildi', 'Reddedildi')], default='Beklemede', max_length=20),
        ),
    ]
