# Generated by Django 5.2 on 2025-04-11 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_adi', models.CharField(max_length=100)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('konu', models.TextField()),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stajlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StajDefteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_no', models.PositiveIntegerField()),
                ('icerik', models.TextField()),
                ('tarih', models.DateField(auto_now_add=True)),
                ('staj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defter_girdileri', to='staj.staj')),
            ],
        ),
    ]
